---
- hosts: pgclu1_cluster
  become: True
  vars_files:
    - vars/main.yaml

  roles: 
    - firewall
    - selinux
    - sysctl
    - etc_hosts
    - pgdg_repo
    - postgres_packages
    - postgres_limits

  tasks:

    - name: "Install packages required for patroni"
      yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        disable_gpg_check: yes
        update_cache: no
      loop: "{{ patroni_packages | list }}"

    - name: "Install patroni with pip"
      ansible.builtin.pip:
        name: "{{ item.name }}"
        executable: "/usr/local/bin/pip3"
      loop: "{{ patroni_pip_packages | list }}"