---
- hosts: pgclu1_cluster
  become: True
  vars_files:
    - vars/main.yaml

  roles: 
    - firewall
    - selinux
    - sysctl
    - etc_hosts
    - pgdg_repo
    - postgres_packages
    - postgres_limits

  tasks:

    - name: "Install packages required for patroni"
      yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        disable_gpg_check: yes
        update_cache: no
      loop: "{{ patroni_packages | list }}"

    - name: Copy patroni requirements.txt file
      copy:
        src: requirements.txt
        dest: /tmp/requirements.txt

    - name: Install requirements
      pip:
        requirements: /tmp/requirements.txt
        executable: pip3
        extra_args: "--trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org"
        umask: "0022"
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/pgsql-13/bin:/usr/local/bin:/usr/bin"
