---
- hosts: pgclu1_cluster
  become: True
  vars_files:
    - vars/main.yaml

  roles: 
    - firewall
    - selinux
    - sysctl
    - etc_hosts
    - pgdg_repo
    - postgres_packages
    - postgres_limits
    - patroni_repo_packages
    - patroni_pip_packages

  tasks:
    
    - name: "Create PGDATA directory"
      file:
        path: "{{ pg_data_dir }}"
        state: directory
        owner: "{{ pg_user }}"
        group: "{{ pg_user }}"
        mode: 0700

    - name: "Edit .bash_profile of postgres user"
      ansible.builtin.template: 
        src: templates/.bash_profile.j2
        dest: /var/lib/pgsql/.bash_profile
        owner: "{{ pg_user }}"
        group: "{{ pg_user }}"
        mode: 0700

    - name: "Create patroni log directory"
      file:
        path: "{{ patroni_os_log_dir }}"
        state: directory
        owner: "{{ pg_user }}"
        group: "{{ pg_user }}"
        mode: 0700
      tags: patroni_config

    - name: "Create patroni config directory"
      file:
        path: "{{ patroni_os_config_dir }}"
        state: directory
        owner: "{{ pg_user }}"
        group: "{{ pg_user }}"
        mode: 0700
      tags: patroni_config

    - name: "Create patroni config file"
      template:
        src: templates/patroni.yaml.j2
        dest: "{{ patroni_config_file }}"
        owner: "{{ pg_user }}"
        group: "{{ pg_user }}"
      tags: patroni_config
        
    - name: "Create patroni service"
      template:
        src: templates/patroni.service.j2
        dest: "{{ patroni_service_file }}"
      tags: patroni_config

    - name: "Enable patroni service"
      service:
        name: patroni
        enabled: yes
      tags: patroni_config

- hosts: pgclu1_master
  become: True
  vars_files:
    - vars/main.yaml
  tasks:
    - name: "Start patroni service on master"
      service:
        name: patroni
        state: started

- hosts: pgclu1_slaves
  become: True
  vars_files:
    - vars/main.yaml
  tasks:
    - name: "Start patroni service on slaves"
      service:
        name: patroni
        state: started
