---
- hosts: pgclu1_cluster
  become: True
  vars_files:
    - vars/main.yaml

  roles: 
    - firewall
    - selinux
    - sysctl
    - etc_hosts
    - pgdg_repo
    - postgres_packages
    - postgres_limits

  tasks:

    - name: "Install packages required for patroni"
      yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        disable_gpg_check: yes
        update_cache: no
      loop: "{{ patroni_packages | list }}"

    - name: "Install patroni with pip"
      ansible.builtin.pip:
        name: "{{ item.name }}"
        virtualenv_python: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/pgsql-13/bin:/usr/local/bin:/usr/bin"
      loop: "{{ patroni_pip_packages | list }}"