scope: cluster1
namespace: /db/
name: pgclu1-node1
log:
  dir: /var/log/patroni
  level: INFO
restapi:
  listen: 10.0.2.31:8008
  connect_address: 10.0.2.31:8008
etcd3:
  hosts: 10.0.2.21:2379,10.0.2.22:2379,10.0.2.23:2379
  protocol: http
bootstrap:
  dcs:
    ttl: 30
    oop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - local all all trust
    - host all all ::/0 md5
    - host all all 127.0.0.1/32 md5
    - host all all 10.0.2.31/32 md5
    - host all all 10.0.2.32/32 md5
    - host replication repuser ::/0 md5
    - host replication repuser 127.0.0.1/32 md5
    - host replication repuser 10.0.2.31/32 md5
    - host replication repuser 10.0.2.32/32 md5
    - host all zbx_monitor 127.0.0.1/32 trust
    - host all zbx_monitor 0.0.0.0/0 md5
    - host all zbx_monitor ::0/0 md5
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: "*:5432"
  connect_address: 10.0.2.31:5432
  data_dir: /data/pg
  config_dir: /data/pg
  bin_dir : /usr/pgsql-13/bin
#    pgpass: /tmp/pgpass
  authentication:
    replication:
      username: repuser
      password: repuser
    superuser:
      username: patroni
      password: patroni
  parameters:
#        unix_socket_directories: '/tmp'
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
