    - name: "Install patroni with pip"
      ansible.builtin.pip:
        name: "{{ item.name }}"
        virtualenv_python: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/pgsql-13/bin:/usr/local/bin:/usr/bin"
      loop: "{{ patroni_pip_packages | list }}"